/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portlet.js.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import com.liferay.portlet.js.model.JSEntry;
import com.liferay.portlet.js.service.JSEntryLocalService;
import com.liferay.portlet.js.service.JSEntryService;
import com.liferay.portlet.js.service.persistence.JSEntryPersistence;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the j s entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portlet.js.service.impl.JSEntryLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portlet.js.service.impl.JSEntryLocalServiceImpl
 * @see com.liferay.portlet.js.service.JSEntryLocalServiceUtil
 * @generated
 */
public abstract class JSEntryLocalServiceBaseImpl implements JSEntryLocalService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.portlet.js.service.JSEntryLocalServiceUtil} to access the j s entry local service.
	 */

	/**
	 * Adds the j s entry to the database. Also notifies the appropriate model listeners.
	 *
	 * @param jsEntry the j s entry to add
	 * @return the j s entry that was added
	 * @throws SystemException if a system exception occurred
	 */
	public JSEntry addJSEntry(JSEntry jsEntry) throws SystemException {
		jsEntry.setNew(true);

		return jsEntryPersistence.update(jsEntry, false);
	}

	/**
	 * Creates a new j s entry with the primary key. Does not add the j s entry to the database.
	 *
	 * @param jsEntryId the primary key for the new j s entry
	 * @return the new j s entry
	 */
	public JSEntry createJSEntry(long jsEntryId) {
		return jsEntryPersistence.create(jsEntryId);
	}

	/**
	 * Deletes the j s entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param jsEntryId the primary key of the j s entry to delete
	 * @throws PortalException if a j s entry with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteJSEntry(long jsEntryId)
		throws PortalException, SystemException {
		jsEntryPersistence.remove(jsEntryId);
	}

	/**
	 * Deletes the j s entry from the database. Also notifies the appropriate model listeners.
	 *
	 * @param jsEntry the j s entry to delete
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteJSEntry(JSEntry jsEntry) throws SystemException {
		jsEntryPersistence.remove(jsEntry);
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return jsEntryPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @param start the lower bound of the range of model instances to return
	 * @param end the upper bound of the range of model instances to return (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return jsEntryPersistence.findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @param start the lower bound of the range of model instances to return
	 * @param end the upper bound of the range of model instances to return (not inclusive)
	 * @param orderByComparator the comparator to order the results by
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return jsEntryPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Counts the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return jsEntryPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Gets the j s entry with the primary key.
	 *
	 * @param jsEntryId the primary key of the j s entry to get
	 * @return the j s entry
	 * @throws PortalException if a j s entry with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public JSEntry getJSEntry(long jsEntryId)
		throws PortalException, SystemException {
		return jsEntryPersistence.findByPrimaryKey(jsEntryId);
	}

	/**
	 * Gets the j s entry with the UUID and group id.
	 *
	 * @param uuid the UUID of j s entry to get
	 * @param groupId the group id of the j s entry to get
	 * @return the j s entry
	 * @throws PortalException if a j s entry with the UUID and group id could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public JSEntry getJSEntryByUuidAndGroupId(String uuid, long groupId)
		throws PortalException, SystemException {
		return jsEntryPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Gets a range of all the j s entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of j s entries to return
	 * @param end the upper bound of the range of j s entries to return (not inclusive)
	 * @return the range of j s entries
	 * @throws SystemException if a system exception occurred
	 */
	public List<JSEntry> getJSEntries(int start, int end)
		throws SystemException {
		return jsEntryPersistence.findAll(start, end);
	}

	/**
	 * Gets the number of j s entries.
	 *
	 * @return the number of j s entries
	 * @throws SystemException if a system exception occurred
	 */
	public int getJSEntriesCount() throws SystemException {
		return jsEntryPersistence.countAll();
	}

	/**
	 * Updates the j s entry in the database. Also notifies the appropriate model listeners.
	 *
	 * @param jsEntry the j s entry to update
	 * @return the j s entry that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public JSEntry updateJSEntry(JSEntry jsEntry) throws SystemException {
		jsEntry.setNew(false);

		return jsEntryPersistence.update(jsEntry, true);
	}

	/**
	 * Updates the j s entry in the database. Also notifies the appropriate model listeners.
	 *
	 * @param jsEntry the j s entry to update
	 * @param merge whether to merge the j s entry with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the j s entry that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public JSEntry updateJSEntry(JSEntry jsEntry, boolean merge)
		throws SystemException {
		jsEntry.setNew(false);

		return jsEntryPersistence.update(jsEntry, merge);
	}

	/**
	 * Gets the j s entry local service.
	 *
	 * @return the j s entry local service
	 */
	public JSEntryLocalService getJSEntryLocalService() {
		return jsEntryLocalService;
	}

	/**
	 * Sets the j s entry local service.
	 *
	 * @param jsEntryLocalService the j s entry local service
	 */
	public void setJSEntryLocalService(JSEntryLocalService jsEntryLocalService) {
		this.jsEntryLocalService = jsEntryLocalService;
	}

	/**
	 * Gets the j s entry remote service.
	 *
	 * @return the j s entry remote service
	 */
	public JSEntryService getJSEntryService() {
		return jsEntryService;
	}

	/**
	 * Sets the j s entry remote service.
	 *
	 * @param jsEntryService the j s entry remote service
	 */
	public void setJSEntryService(JSEntryService jsEntryService) {
		this.jsEntryService = jsEntryService;
	}

	/**
	 * Gets the j s entry persistence.
	 *
	 * @return the j s entry persistence
	 */
	public JSEntryPersistence getJSEntryPersistence() {
		return jsEntryPersistence;
	}

	/**
	 * Sets the j s entry persistence.
	 *
	 * @param jsEntryPersistence the j s entry persistence
	 */
	public void setJSEntryPersistence(JSEntryPersistence jsEntryPersistence) {
		this.jsEntryPersistence = jsEntryPersistence;
	}

	/**
	 * Gets the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Gets the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Gets the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Gets the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Gets the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Gets the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Gets the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query to perform
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = jsEntryPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = JSEntryLocalService.class)
	protected JSEntryLocalService jsEntryLocalService;
	@BeanReference(type = JSEntryService.class)
	protected JSEntryService jsEntryService;
	@BeanReference(type = JSEntryPersistence.class)
	protected JSEntryPersistence jsEntryPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}