/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portlet.js.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the JSEntry service. Represents a row in the &quot;JS_JSEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.portlet.js.model.impl.JSEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.portlet.js.model.impl.JSEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see JSEntry
 * @see com.liferay.portlet.js.model.impl.JSEntryImpl
 * @see com.liferay.portlet.js.model.impl.JSEntryModelImpl
 * @generated
 */
public interface JSEntryModel extends BaseModel<JSEntry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a j s entry model instance should use the {@link JSEntry} interface instead.
	 */

	/**
	 * Gets the primary key of this j s entry.
	 *
	 * @return the primary key of this j s entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this j s entry
	 *
	 * @param pk the primary key of this j s entry
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the uuid of this j s entry.
	 *
	 * @return the uuid of this j s entry
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this j s entry.
	 *
	 * @param uuid the uuid of this j s entry
	 */
	public void setUuid(String uuid);

	/**
	 * Gets the js entry id of this j s entry.
	 *
	 * @return the js entry id of this j s entry
	 */
	public long getJsEntryId();

	/**
	 * Sets the js entry id of this j s entry.
	 *
	 * @param jsEntryId the js entry id of this j s entry
	 */
	public void setJsEntryId(long jsEntryId);

	/**
	 * Gets the create date of this j s entry.
	 *
	 * @return the create date of this j s entry
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this j s entry.
	 *
	 * @param createDate the create date of this j s entry
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Gets the modified date of this j s entry.
	 *
	 * @return the modified date of this j s entry
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this j s entry.
	 *
	 * @param modifiedDate the modified date of this j s entry
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Gets the js of this j s entry.
	 *
	 * @return the js of this j s entry
	 */
	@AutoEscape
	public String getJs();

	/**
	 * Sets the js of this j s entry.
	 *
	 * @param js the js of this j s entry
	 */
	public void setJs(String js);

	/**
	 * Gets the class name of the model instance this j s entry is polymorphically associated with.
	 *
	 * @return the class name of the model instance this j s entry is polymorphically associated with
	 */
	public String getClassName();

	/**
	 * Gets the class name id of this j s entry.
	 *
	 * @return the class name id of this j s entry
	 */
	public long getClassNameId();

	/**
	 * Sets the class name id of this j s entry.
	 *
	 * @param classNameId the class name id of this j s entry
	 */
	public void setClassNameId(long classNameId);

	/**
	 * Gets the class p k of this j s entry.
	 *
	 * @return the class p k of this j s entry
	 */
	public long getClassPK();

	/**
	 * Sets the class p k of this j s entry.
	 *
	 * @param classPK the class p k of this j s entry
	 */
	public void setClassPK(long classPK);

	/**
	 * Gets the group id of this j s entry.
	 *
	 * @return the group id of this j s entry
	 */
	public long getGroupId();

	/**
	 * Sets the group id of this j s entry.
	 *
	 * @param groupId the group id of this j s entry
	 */
	public void setGroupId(long groupId);

	/**
	 * Gets the version of this j s entry.
	 *
	 * @return the version of this j s entry
	 */
	public double getVersion();

	/**
	 * Sets the version of this j s entry.
	 *
	 * @param version the version of this j s entry
	 */
	public void setVersion(double version);

	/**
	 * Gets the status of this j s entry.
	 *
	 * @return the status of this j s entry
	 */
	public int getStatus();

	/**
	 * Sets the status of this j s entry.
	 *
	 * @param status the status of this j s entry
	 */
	public void setStatus(int status);

	/**
	 * Gets the status date of this j s entry.
	 *
	 * @return the status date of this j s entry
	 */
	public Date getStatusDate();

	/**
	 * Sets the status date of this j s entry.
	 *
	 * @param statusDate the status date of this j s entry
	 */
	public void setStatusDate(Date statusDate);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(JSEntry jsEntry);

	public int hashCode();

	public JSEntry toEscapedModel();

	public String toString();

	public String toXmlString();
}